M48
; DRILL file {KiCad (5.99.0-12267-gfe608bfcef)} date Sun Nov  7 23:23:36 2021
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2021-11-07T23:23:36+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(5.99.0-12267-gfe608bfcef)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
%
G90
G05
T1
X141.91Y-88.32
X147.69Y-88.32
T0
M30
